---
name: PR Heimgewebe commands

"on":
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  dispatch:
    if: github.event.issue.pull_request != null
    uses: heimgewebe/metarepo/.github/workflows/heimgewebe-command-dispatch.yml@main
    secrets:
      HEIMGEWEBE_APP_ID: ${{ secrets.HEIMGEWEBE_APP_ID }}
      HEIMGEWEBE_APP_PRIVATE_KEY: ${{ secrets.HEIMGEWEBE_APP_PRIVATE_KEY }}
      HEIMGEWEBE_AUTOBOT_TOKEN: ${{ secrets.HEIMGEWEBE_AUTOBOT_TOKEN }}
